// circular linked list
#include "structNode.hpp"
int main(){
    Snode* head = new Snode({"head_node", NULL});
    Snode* temp = new Snode({"new_node", NULL});
    Snode* temp2 = new Snode({"third_node", NULL});
    Snode* temp3 = new Snode({"fourth_node", NULL});
    Snode* empty = NULL;
    head->next = head;
    temp->next = temp;
    temp2->next = temp2;
    temp3->next = temp3;
    cout << " temp: \n";
    Display(temp);
    cout << " temp2: \n";
    Display(temp2);
    cout << " temp3: \n";
    Display(temp3);
    cout << " head: \n";
    Display(head);
    cout << " empty: \n";
    Display(empty);
    cout << " after insertion 1\n";
    insertCnode(empty, head);
    cout << " temp: \n";
    Display(temp);
    cout << " temp2: \n";
    Display(temp2);
    cout << " temp3: \n";
    Display(temp3);
    cout << " head: \n";
    Display(head);
    cout << " empty: \n";
    Display(empty);
    cout << " after insertion 2\n";
    insertCnode(empty, temp, 1);
    cout << " temp: \n";
    Display(temp);
    cout << " temp2: \n";
    Display(temp2);
    cout << " temp3: \n";
    Display(temp3);
    cout << " head: \n";
    Display(head);
    cout << " empty: \n";
    Display(empty);
    cout << " after insertion 3\n";
    insertCnode(empty, temp2, 2);
    cout << " temp: \n";
    Display(temp);
    cout << " temp2: \n";
    Display(temp2);
    cout << " temp3: \n";
    Display(temp3);
    cout << " head: \n";
    Display(head);
    cout << " empty: \n";
    Display(empty);
    cout << " after insertion 4\n";
    insertCnode(empty, temp3, 2);
    cout << " temp: \n";
    Display(temp);
    cout << " temp2: \n";
    Display(temp2);
    cout << " temp3: \n";
    Display(temp3);
    cout << " head: \n";
    Display(head);
    cout << " empty: \n";
    Display(empty);
}